simulation_name: ""
simulation_description: ""
nodes:
  citizen:
    initial_numbers: 10
    connectivity:
      type: percentage
      percentage: 0.6
    modules:
      health:
        age:
          range: [360, 720]
          distribution:
            type: normal
            mean: 450
            std: 100
        health:
          range: [50, 100]
          distribution:
            type: normal
            mean: 80
            std: 10
        baseline_hazard:
          range: [8.0e-6, 8.0e-6]
          distribution:
            type: constant
            value: 8.0e-6
        rate_of_aging:
          range: [0.0080, 0.0080]
          distribution:
            type: constant
            value: 0.0080
        ind_background_hazard:
          range: [6.0e-5, 6.0e-5]
          distribution:
            type: constant
            value: 6.0e-5
        max_age:
          range: [1200, 1200]
          distribution:
            type: constant
            value: 1200
  governament:
    initial_numbers: 1
    connectivity:
      type: constant
      value: 1
    modules:
      money:
        balance:
          range: [100_000_000, 100_000_000]
          distribution:
            type: constant
            value: 100_000_000
        income:
          range: [0, 0]
          distribution:
            type: constant
            value: 0
simulation:
  step_size: 1 month
  max_duration: 48
  re_connection: False
  seed: 2026
  nr_runs: 10
